### ISSUE TITLE
USB based cams or multiple cameras

### ISSUE THREAD

**Issue by storagejarett** [NVIDIA-AI-IOT/jetbot#13]
Given the limited availability of the 140-150 degree FOV webcam, it would be beneficial to use USB based webcams, or more than 1 narrower field of view webcam.  

Alternatively, using FPV Drone cameras (cheaper, simple 3 wire) with wide angle lens would be useful as well. 

USB webcams are popular in the RPi world, as most drivers are already baked into standard V4L of distributions.

**Comment by jaybdub** [comment]
Hi storagejarett,

Cool idea!  We chose the CSI camera because it's low cost and low latency, but perhaps a fork of this project using a USB camera would be helpful to others.

The easiest way to test this out would be to fork this project and modify the bill of materials, camera_mount.stl, and ``jetbot.Camera`` class accordingly.  

If you make a fork of the jetbot project that you think would be useful to others please let us know!

Thanks!
John
