### ISSUE TITLE
PiOLED not displaying

### ISSUE THREAD

**Issue by Sgilroy343** [NVIDIA-AI-IOT/jetbot#139]
Hey,

Currently I am having an issue with the PiOLED not displaying anything if the 3V3 pin (Red pin on the images in hardware setup) is connected. If this pin is not connected, the PiOLED displayed all available information. Does anyone have any idea of this issue?

Thanks

**Comment by cagriy** [comment]
With the pin connected, does both of your motors working as expected ? And none of the motors working when it is disconnected but PiOLED is working ?

If motors working just fine while connected, then we can assume motor controller is fine. Otherwise it may be faulty.

2 other things to check

1 - Are you getting power from a decent source ? If you don't have enough watts it may be the case that the load from controller leaving not enough power for the led.
2 - Has Jetson in 5W mode ? Because of the same reason.
3 - Please re-check cabling on each end, a mismatch is very likely to cause this kind of issue.
