### ISSUE TITLE
TB6612

### ISSUE THREAD

**Issue by Agent-Cain** [NVIDIA-AI-IOT/jetbot#33]
What is the advantage of the featherboard over a normal breakoutboard ?

**Comment by aussetg** [comment]
It also includes a PCA6985 so you only have to send commands via I2C instead of a raw PWM output which I don't think the Jetson can provide.

I bough the Adafruit version but it's definitely overpriced, I'' buy an aliexpress copy and compare them. (just search for PCA6985 + TB6612 on Ali) Hopefully they are nice, not many reviews
