### ISSUE TITLE
Event code not working

### ISSUE THREAD

**Issue by fciampoli** [NVIDIA-AI-IOT/jetbot#36]
Event code DLI_Jet_Demo is not working on https://courses.nvidia.com/dli-event in your web browser

**Comment by revox0x** [comment]
I have the same problem.

**Comment by jaybdub** [comment]
Hi All,

Thanks for reaching out.  Sorry, the training instructions in the Wiki were outdated.  I've updated the Wiki to include instructions for training on the Jetson Nano or on an external GPU enabled machine. 

Please let me know if you run into any issues, or otherwise if this works for you!

Thanks!
John
