### ISSUE TITLE
Printable road for road following

### ISSUE THREAD

**Issue by kiwibruyanta** [NVIDIA-AI-IOT/jetbot#431]
Hello,

i'm looking for a printable road that could be used for the notebook road following. I would like a road similar to the lego tracks used in the videos or similar to the one used in this video https://www.youtube.com/watch?v=ELZWrAmx8jk . Unfortunately i didn't find a model like that on internet.

thank you,

**Comment by tokk-nv** [comment]
Hello kiwibruyanta,
Since you are collecting the data to train your model by yourself as well, you don't need to stick with the LEGO plate, but you can use any design road plate you like.
So you can draw couple of patterns using any drawing software you like (GIMP, Inkscape being free options), and print them out.

An article like the below may give you more ideas.
https://www.whilehewasnapping.com/printable-diy-race-track-kids-love

**Comment by DingoOz** [comment]
I used black building plastic and masking tape to create a road that can pack away easily: https://adventuresinsilicon.blogspot.com/2021/01/cheap-and-easy-robot-racetrack-or-line.html

**Comment by AnbuKumar-maker** [comment]
> Hello,
> 
> i'm looking for a printable road that could be used for the notebook road following. I would like a road similar to the lego tracks used in the videos or similar to the one used in this video https://www.youtube.com/watch?v=ELZWrAmx8jk . Unfortunately i didn't find a model like that on internet.
> 
> thank you,


Hello, you may use the attached PDF to print a nice race track road, I used this to train my JetBot for Road Following
[https://github.com/AnbuKumar-maker/Printable-Road-For-NVIDIA-JetBot](url)
