### ISSUE TITLE
Can jetbot be used in Jetson xavier NX  ?

### ISSUE THREAD

**Issue by AmazingYi** [NVIDIA-AI-IOT/jetbot#432]
I have  a jetson xavier nx board with develop kit .  I have  some  other aplication out of the capacity of Nano ,  so I choose  NX . But  I still want to use   jetbot to make a moving platform for it.    Can I install jetbot  on the NX.  I means that  change to a 19V power  and same parameters   or some python files  . Is it feasible ？ if  so,  Is there any sample about it ?

**Comment by tokk-nv** [comment]
Hi AmazingYi,

We have not tested with Jetson Xavier NX dev kit by ourselves, although are aware some people tried.

Since we have the Docker containers, in theory, it should be easy to at least try it out on Jetson Xavier NX.
http://jetbot.org/v0.4.3/software_setup/docker.html

As to the power, Jetson Xavier NX Dev Kit carrier board requires 9-20V on it's DC Jack, so if you are using a Waveshare JetBot kit, you could probably just use the battery voltage (VBATT) off from its 3-cell battery.

Let us know how it goes!
If you run into any issues with running the containers on Jetson Xavier NX, please let us know.
