### ISSUE TITLE
Jetbot JetPack 4.2 does not work

### ISSUE THREAD

**Issue by gwiheo** [NVIDIA-AI-IOT/jetbot#487]
I had difficulty in setting up JetPack 4.2 since the 4.2 image does not boot after flashing it on the micro sd card. When I tried to install the 4.3 version of JetPack, I did not have any problem, but the 4.2 version did not work. 

I tried  with jetbot_image_v0p3p2.zip found at the link below, but it doesn't work.
https://jetbot.org/master/software_setup/sd_card.html

I tried also with jetbot_image_v0p3p0.zip found at this link : https://github.com/NVIDIA-AI-IOT/jetbot/releases. But this one also does not work.

The reason to use old Jetbot JetPack version of 4.2 : I am trying to learn about RL work done at below github whoes code only work at 4.2 version.
https://github.com/masato-ka/airc-rl-agent

**Comment by AI-adventurer** [comment]
Me too.

**Comment by santaimpersonator** [comment]
From my experience, once you've flashed the new firmware with the `oem-config` tool in the Jetpack 4.5 image, you are restricted to the pre-built images with Jetpack version 4.3 and later _(the new firmware doesn't work with pre-built images using Jetpack 4.2 and earlier)_.

**Comment by gwiheo** [comment]
@santaimpersonator  Thank you for your kind comment. I like Sparkfun and miss Boulder where I had lived for a short period of time.

**Comment by santaimpersonator** [comment]
@gwiheo No problem. Thanks for your support.

You may want to try checking out the `jetbot-043_nano-4gb-jp45.zip` image from [jetbot.org](http://jetbot.org/master/software_setup/sd_card.html): ![image](https://user-images.githubusercontent.com/36016723/143893700-8a5a672f-94bc-407b-9d17-4d5923d8640e.png)
If I remember correctly, there were some commands in the bash history, that looked like they were used to rebuild the image around a specific release. However, I can't remember if it was for a `JetBot` or `JetPack` release.

Otherwise, you may want to look at the Nvidia Jetpack developer documentation: https://docs.nvidia.com/jetson/jetpack/index.html

* You might be able to use other methods, like the [SDK Manager](https://docs.nvidia.com/jetson/jetpack/install-jetpack/index.html#sdk-manager) to install JetPack 4.2

That's about as much as I can think of to help out on this topic. For more assistance, you may need to go to the [Nvidia forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70) to ask if there is a way to use JetPack 4.2 with the new firmware on the Jetson Nano.
