### ISSUE TITLE
How to apply changes on jetbot

### ISSUE THREAD

**Issue by amirziou** [NVIDIA-AI-IOT/jetbot#535]
Hi,
Im using the pre-built JetBot SD card image for jetbot and everything is working well. Im now trying to modify things in the codes (like modifying robot.py file) and the changes does not apply. I new after that I have to build my own base image and then run it and I don’t know how to that, can someone please guide me to what I have to do? how can I make it save changes?

**Comment by jaybdub** [comment]
Hi @amirziou ,

Thanks for reaching out!

This probably has to do with what happens when Docker restarts, or the Python interpreter path

1. You're editing the ``robot.py`` that is pre-installed inside the docker container.  This will get overwritten when you restart the container.
2. You're *are* editing a ``robot.py`` located on a persistent volume (your Jupyter Notebooks are stored on a mounted volume), however when you restart the container, Python 'forgets' that you had installed this package, and doesn't look for it.  

Do you mind sharing the full path to the ``robot.py`` file that you're editing?

Best,
John
