### ISSUE TITLE
It is not booting. No GUI Display

### ISSUE THREAD

**Issue by anandbharadwaj1** [NVIDIA-AI-IOT/jetbot#537]
![WhatsApp Image 2022-06-01 at 5 57 35 PM](https://user-images.githubusercontent.com/83603991/171404435-717b0285-4f92-450b-a42b-def31d874fa2.jpeg)

**Comment by ThaiVuz** [comment]
i also have a problem like you ? If you know how to fix it please help me !!!!

**Comment by jaybdub** [comment]
Hi All,

Thansk for reaching out.

To conserve memory consumption, we disable the GUI on JetBot by default (since it's programmed over a Jupyter Web server).

If you want to re-enable the GUI, you can execute the following command.

```bash
sudo systemctl set-default graphical.target
```

You can find more details on [this page](http://jetbot.org/master/software_setup/docker.html).

Hope this helps, please let me know if you have any questions or run into any issues.

Best,
John
