### ISSUE TITLE
Creating SD Card Image From Scratch - traitlets installation Issue

### ISSUE THREAD

**Issue by pradrn** [NVIDIA-AI-IOT/jetbot#540]
Hi,

I have a Jetson Nano 2GB Developer Kit with me. I am trying to create a jetbot SD card image from scratch. I was following the steps present in the Wiki and all was good until I encountered the installation of Traitlets. The command mentioned in the wiki is as follows: `sudo python3 -m pip install git+https://github.com/ipython/traitlets@master`. 

This was throwing an error as @master branch has been renamed to @main, so i modified the code to 
`sudo python3 -m pip install git+https://github.com/ipython/traitlets@main`.

![Screenshot from 2022-06-07 15-18-40](https://user-images.githubusercontent.com/40749183/172537773-27f1595c-4051-4419-b867-0c890d29a36e.png)

As you can see, this is the error i am encountering right now. Can you please help me solve this. I have both python 3.6.9 and python 2.7.17 running on the jetson nano.

![Screenshot from 2022-06-07 15-21-01](https://user-images.githubusercontent.com/40749183/172538006-1e6edc97-5344-4638-a368-c1947c01fd22.png)

**Comment by jaybdub** [comment]
Hi @pradrn ,

Thanks for reaching out!

Do you encounter the same error when you install the default ``traitlets`` package?

```bash
python3 -m pip install traitlets
```

The master branch was used to support the ``unlink`` method.  But you may not need this method, or perhaps it's already been integrated into a stable version since this was done some time ago.

Let me know if you have any questions.

Best,
John
