### ISSUE TITLE
Left deviation

### ISSUE THREAD

**Issue by ddwy** [NVIDIA-AI-IOT/jetbot#68]
Why does my jetbot go left when going straight and backward?

**Comment by aileenZhang** [comment]
Maybe you should check your power bank

**Comment by jaybdub** [comment]
Hi ddwy,

Usually, due to slippage, friction and other factors throughout the system, the robot will either tend slightly to the right or left.  If the drift is extreme, could you check to see if there is anything adding resistance to one of the wheels?

Is the robot spinning in place?  If so, one of the motors may be wired backwards.

John

**Comment by ddwy** [comment]
> Hi ddwy,
> 
> Usually, due to slippage, friction and other factors throughout the system, the robot will either tend slightly to the right or left. If the drift is extreme, could you check to see if there is anything adding resistance to one of the wheels?
> 
> Is the robot spinning in place? If so, one of the motors may be wired backwards.
> 
> John

Hello, my situation is like this. When the car moves forward, it will move slowly to the left.

**Comment by wjzhou** [comment]
I think this is unavoidable in the current open-loop control setup.
Even with the same pwm, the motors will spin slightly differently,  the car will turn slowly.

You may hold the cart, and check both motor spins as expected

**Comment by ddwy** [comment]
The problem has not been solved yet.

**Comment by einsteinagogo** [comment]
or because motors have different deviations!

The TT Motor described here on the PiHiut states

https://thepihut.com/products/adafruit-dc-gearbox-motor-tt-motor-200rpm-3-to-6vdc-ada3777

Note that these are very basic motors, and have no built-in encoders, speed control or positional feedback. Voltage goes in, rotation goes out! T**here will be variation from motor to motor**, so a separate feedback system is required if you need precision movement.

mine is also the same.

**Comment by jaybdub** [comment]
Yep!  

Drift is unavoidable with this open-loop control scheme.  By calibrating, you can reduce the rate that the robot drifts.

Actually, the motor implementation has an ``alpha`` and ``beta`` value which may be used to linearly calibrate each motor.  The command, ``y`` sent to the motor is calculated from the input value ``x`` as

``y = alpha * x + beta``

You could adjust these parameters to linearly calibrate each motor with software.  For example,

```python
robot.left_motor.alpha = 0.3
robot.right_motor.alpha = 0.7
```

Attaching them to sliders will probably make live calibration a lot easier.  The results wont be perfect, but might help a bit.

Please let me know if you have any questions.

Best,
John

**Comment by einsteinagogo** [comment]
I also found that using a better battery, for motors and Jetson Nano, deviation was less! and the robot could be controlled and go forward with less calibration.

Still needs a little tweaking, but worth checking if you battery can supply what is required.

**Comment by LuisM78** [comment]
I am having the same proble. Do you know of a better robot platform for the jetson nano?
Thanks,
Luis
